# Generated by Django 4.0 on 2022-01-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0005_alter_animalshelter_contact_no_alter_pet_gender_and_more'),
        ('pet_finder', '0006_rename_name_animalshelter_organisations_name_and_more'),
    ]

    operations = [
    ]
