# Generated by Django 4.0 on 2022-01-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0007_merge_20220130_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='third_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='second_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccination',
            field=models.CharField(choices=[('Not Vaccianted', 'Not Vaccianted'), ('Partially Vaccinated', 'Partially Vaccinated'), ('Completely vaccinated', 'Completely Vaccinated')], max_length=30),
        ),
    ]
