# Generated by Django 4.0 on 2022-01-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0005_alter_animalshelter_contact_no'),
        ('pet_finder', '0008_pet_third_image_alter_pet_age_alter_pet_second_image_and_more'),
    ]

    operations = [
    ]
