# Generated by Django 4.0 on 2022-02-08 11:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0010_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('street_address', models.CharField(blank=True, max_length=300, null=True)),
                ('pincode', models.IntegerField(help_text='6 digits [0-9] PIN code', validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='PIN code')),
                ('house', models.CharField(choices=[('rent', 'rent'), ('own house', 'own house')], max_length=15)),
                ('is_allergies', models.BooleanField(default=False)),
                ('is_fenced', models.BooleanField(default=False)),
                ('why_do_you_want_a_dog', models.TextField()),
                ('dog_be_confined_to_your_own_property', models.TextField()),
                ('provide_exercise', models.TextField()),
                ('training_willing_to_provide', models.TextField()),
                ('correct_dog_if_misbehaves', models.TextField()),
                ('takes_to_support_a_dog', models.TextField()),
                ('choose_this_particular_dog', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_form_user', to='pet_finder.user')),
            ],
        ),
    ]
