# Generated by Django 4.0 on 2022-02-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0015_adoptionform_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pincode',
        ),
    ]
