# Generated by Django 4.0 on 2022-02-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0016_remove_pet_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='animal_shelter',
            new_name='animalshelter',
        ),
    ]
