# Generated by Django 4.0 on 2022-02-14 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0017_rename_animal_shelter_pet_animalshelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='second_image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='third_image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
