# Generated by Django 4.0 on 2022-02-14 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0018_alter_pet_second_image_alter_pet_third_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionform',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_form_pet', to='pet_finder.pet'),
            preserve_default=False,
        ),
    ]
