# Generated by Django 4.0 on 2022-02-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0020_remove_adoptionform_pincode_adoptionform_user_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionform',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_form_user_info', to='pet_finder.userinfo'),
        ),
    ]
