# Generated by Django 4.0 on 2022-02-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0021_alter_adoptionform_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionform',
            old_name='send_form_to',
            new_name='animal_shelter_id',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='adoptionform',
            old_name='user_info',
            new_name='user_info_id',
        ),
    ]
