# Generated by Django 4.0 on 2022-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0023_animalshelter_adoption_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionform',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
