# Generated by Django 4.0 on 2022-02-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0025_alter_adoptionform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalshelter',
            name='profile_pic',
            field=models.ImageField(default='1', upload_to='media/'),
            preserve_default=False,
        ),
    ]
