# Generated by Django 4.0 on 2022-02-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0026_animalshelter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vaccination',
            field=models.CharField(choices=[('Not Vaccianted', 'Not Vaccianted'), ('Partially Vaccinated', 'Partially Vaccinated'), ('Completely Vaccinated', 'Completely Vaccinated')], max_length=30),
        ),
    ]
