# Generated by Django 4.0 on 2022-02-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0029_adoptionform_updated_at_animalshelter_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalshelter',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
